updated BISU to v10.2.80
Improved robustness, performance and consistency;
Issue fixes;

diff --git a/bisu/bisu b/bisu/bisu
--- a/bisu/bisu
+++ b/bisu/bisu
@@ -6,9 +6,9 @@
 ## Official Web Site: https://bisu.cc
 ## Recommended BISU PATH: /usr/local/bin/bisu
 ## Have a fresh installation of BISU by copying and pasting the command below
-## curl -sL https://g.bisu.cc/bisu-file -o ./bisu && chmod +x ./bisu && ./bisu -f install
+## curl -sL https://g.bisu.cc/bisu-file -o ./bisu && chmod +x ./bisu && sudo ./bisu -f install
 # Define BISU VERSION
-export BISU_VERSION="10.2.60"
+export BISU_VERSION="10.2.80"
 # Set BISU's last release date
 export BISU_LAST_RELEASE_DATE="2025-08-18Z"
 # Minimal Bash Version
@@ -107,6 +107,8 @@ UTILITY_VERSION=${UTILITY_VERSION:-"1.0"}
 LAST_RELEASE_DATE=${LAST_RELEASE_DATE:-}
 # Set this utility's doc URI
 UTILITY_INFO_URI=${UTILITY_INFO_URI:-}
+# Set this utility's asc sig file URL
+UTILITY_ASC_FILE_URL=${UTILITY_ASC_FILE_URL:-}
 # Atomic mutex lock switch for single-threaded utilities
 ATOMIC_MUTEX_LOCK=${ATOMIC_MUTEX_LOCK:-"true"}
 # Signature verification switch
@@ -560,13 +562,13 @@ time_ns() {
 }
 
 # BISU file path
-bisu_file() {
+bisu_file_path() {
     printf '%s' "$BISU_FILE_PATH"
 }
 
 # BISU file name
 bisu_filename() {
-    printf '%s' $(basename $(bisu_file))
+    printf '%s' $(basename $(bisu_file_path))
 }
 
 # Function: output a message
@@ -576,7 +578,6 @@ output() {
     in_array "$use_newline" "true" "false" || use_newline="true"
     local log_only=$(trim "$3")
     in_array "$log_only" "true" "false" || log_only="false"
-    local log_file="$(current_log_file)"
 
     # Style tag parsing
     [[ "$message" == *"<"*">"* ]] && {
@@ -788,13 +789,13 @@ output() {
         eval "$(printf '%s ' "$command")" |
             { [[ "$use_newline" == "false" ]] && rtrim "$(cat)" '\n' || cat; } |
             { debug_mode_on && fold -s -w "$LINE_BREAK_LENGTH" || fold -s -w "$LINE_BREAK_LENGTH" 2>/dev/null; } |
-            tee -a -- "$log_file" &>/dev/null ||
+            tee -a -- "$(current_log_file)" &>/dev/null ||
             return 1
     else
         eval "$(printf '%s ' "$command")" |
             { [[ "$use_newline" == "false" ]] && rtrim "$(cat)" '\n' || cat; } |
             { debug_mode_on && fold -s -w "$LINE_BREAK_LENGTH" || fold -s -w "$LINE_BREAK_LENGTH" 2>/dev/null; } |
-            { debug_mode_on && tee -a -- "$log_file" || tee -a -- "$log_file" 2>/dev/null; } ||
+            { debug_mode_on && tee -a -- "$(current_log_file)" || tee -a -- "$(current_log_file)" 2>/dev/null; } ||
             return 1
     fi
 
@@ -975,9 +976,9 @@ current_args() {
     printf '%s' "$CURRENT_ARGS"
 }
 
-# Function: current_file
+# Function: current_file_path
 # Description: According to its naming
-current_file() {
+current_file_path() {
     if [ -z $CURRENT_FILE_PATH ] || ! is_file "$CURRENT_FILE_PATH"; then
         output "Invalid current file path: $CURRENT_FILE_PATH"
         quit
@@ -1014,7 +1015,7 @@ user_backup_dir() {
 # Function: current_dir
 # Description: According to its naming
 current_dir() {
-    printf '%s' $(dirname $(current_file))
+    printf '%s' $(dirname $(current_file_path))
 }
 
 # The current log file
@@ -1060,8 +1061,9 @@ current_log_file() {
         chmod -R 755 "$log_file_dir" &>/dev/null || quit
     }
 
-    touch "$log_file" || quit
-    is_file "$log_file" || quit
+    is_file "$log_file" || {
+        touch "$log_file" &>/dev/null || quit
+    }
 
     printf '%s' "$log_file"
 }
@@ -1142,19 +1144,19 @@ error_exit() {
             local parent_file="${BASH_SOURCE[0]}"
             local parent_lineno="${BASH_LINENO[0]}"
 
-            local current_file=""
+            local current_file_path=""
             local current_lineno=""
 
             for i in "${!BASH_SOURCE[@]}"; do
                 src="${BASH_SOURCE[i]}"
                 if [[ "$src" != "$parent_file" ]]; then
-                    current_file="$src"
+                    current_file_path="$src"
                     current_lineno="${BASH_LINENO[i - 1]:-?}"
                     break
                 fi
             done
 
-            [[ -z "$current_file" ]] && current_file="$parent_file" && current_lineno="$parent_lineno"
+            [[ -z "$current_file_path" ]] && current_file_path="$parent_file" && current_lineno="$parent_lineno"
 
             # For parent file
             local parent_line_text
@@ -1163,10 +1165,10 @@ error_exit() {
             parent_charno=$(awk '{match($0,/[^[:space:]]/); print (RSTART?RSTART:1)}' <<<"$parent_line_text")
             # For current file
             local current_line_text
-            current_line_text=$(sed "${current_lineno}q;d" "$current_file" 2>/dev/null)
+            current_line_text=$(sed "${current_lineno}q;d" "$current_file_path" 2>/dev/null)
             local current_charno
             current_charno=$(awk '{match($0,/[^[:space:]]/); print (RSTART?RSTART:1)}' <<<"$current_line_text")
-            log_add "                              <fg_bright_yellow>(Tracing: ${current_file}:${current_lineno}:${current_charno}, \
+            log_add "                              <fg_bright_yellow>(Tracing: ${current_file_path}:${current_lineno}:${current_charno}, \
 ${parent_file}:${parent_lineno}:${parent_charno}</fg_bright_yellow>)"
         }
         log_flush
@@ -1954,12 +1956,11 @@ debug_mode_on() {
 # Execute command
 exec_command() {
     local phrase=$(trim "$1")
-    local args=""
     string_to_array "$phrase" "phrase"
     normalize_array "phrase"
     local cmd=$(array_get "phrase" 0)
     array_splice "phrase" 0 1
-    args=$(trim "$(printf '%s ' "${phrase[@]}")")
+    local args=$(trim "$(printf '%s ' "${phrase[@]}")")
     phrase="$(printf '%s ' "${cmd} ${args}")"
 
     is_executable "$cmd" || return 1
@@ -1972,19 +1973,23 @@ exec_command() {
 
     log_msg "🕒 Command executing: $phrase" "true"
     if [[ "$run_in_bg" == "false" ]]; then
-        {
-            { debug_mode_on && eval "$(printf '%s' "$phrase")" 2>&1 || eval "$(printf '%s' "$phrase")" 2>/dev/null; } |
-                {
-                    if [[ "$logging" == "true" ]]; then
-                        tee -a -- "$(current_log_file)"
-                    fi
-                }
-        } || {
+        if [[ "$logging" == "true" ]]; then
+            debug_mode_on && eval "$(printf '%s' "$phrase")" 2>&1 || eval "$(printf '%s' "$phrase")" 2>/dev/null |
+                tee -a -- "$(current_log_file)" || {
+                log_msg "❗️ Last execution failure was from: $phrase" "true"
+                return 1
+            }
+        else
+            debug_mode_on && eval "$(printf '%s' "$phrase")" 2>&1 || eval "$(printf '%s' "$phrase")" 2>/dev/null || {
+                log_msg "❗️ Last execution failure was from: $phrase" "true"
+                return 1
+            }
+        fi
+    else
+        pid=$(safe_fork "$phrase" "true" "$logging") || {
             log_msg "❗️ Last execution failure was from: $phrase" "true"
             return 1
         }
-    else
-        pid=$(safe_fork "$phrase" "$logging")
     fi
 
     log_msg "✅ Command execution done: $phrase" "true"
@@ -2003,8 +2008,8 @@ confirm() {
     esac
 
     while [ 0 ]; do
-        log_msg "$message" "false" "false"
-        read -p " $prompt " -r input
+        log_msg "$message" "true"
+        read -p "- ${message} ${prompt} " -r input
 
         # If user just presses Enter, use default
         input=$(trim "$input")
@@ -4330,7 +4335,7 @@ gen_sig_file() {
     fi
 
     if [ -z "$target_file" ]; then
-        target_file=$(current_file)
+        target_file=$(current_file_path)
     fi
 
     if ! is_file "$target_file"; then
@@ -4338,7 +4343,7 @@ gen_sig_file() {
     fi
 
     if [ -z "$sig_file" ]; then
-        if [[ "$target_file" != "$(current_file)" ]]; then
+        if [[ "$target_file" != "$(current_file_path)" ]]; then
             sig_file="${target_file}.asc"
         else
             sig_file="./$(current_filename).asc"
@@ -4381,7 +4386,7 @@ EOF
 # verify_sig_file: Verify a GPG signature with maximum robustness
 # Args:
 #   $1 - signature file path
-#   $2 - source file path (optional, current_file() used if omitted)
+#   $2 - source file path (optional, current_file_path() used if omitted)
 # Output:
 #   If technical errors prints "failed";
 #   If detected hash algorithm prints {algo_name}, else "unknown";
@@ -4396,7 +4401,7 @@ verify_sig_file() {
         return 1
     }
 
-    [ -n "$src_file" ] || src_file="$(current_file)"
+    [ -n "$src_file" ] || src_file="$(current_file_path)"
 
     is_file "$src_file" || {
         printf "failed"
@@ -4932,8 +4937,8 @@ reliable_curl() {
     local CURL_KEY=$(trim "${CURL_KEY:-}")
     local CURL_KEY_PASSPHRASE=$(trim "${CURL_KEY_PASSPHRASE:-}")
     local CURL_EXTRA_OPTS=$(trim "${CURL_EXTRA_OPTS:-}")
-    local CURL_RAW_STATUS_CODE=$(trim "${CURL_RAW_STATUS_CODE:-"false"}")
-    in_array "$CURL_RAW_STATUS_CODE" "true" "false" || CURL_RAW_STATUS_CODE="false"
+    local CURL_USE_RAW_STATUS_CODE=$(trim "${CURL_USE_RAW_STATUS_CODE:-"false"}")
+    in_array "$CURL_USE_RAW_STATUS_CODE" "true" "false" || CURL_USE_RAW_STATUS_CODE="false"
     local CURL_FILE_HASH_ALGO=$(trim "${CURL_FILE_HASH_ALGO:-}")
     CURL_FILE_HASH_ALGO=$(strtolower "$CURL_FILE_HASH_ALGO")
     local CURL_FILE_HASH=$(trim "${CURL_FILE_HASH:-}")
@@ -5242,11 +5247,11 @@ reliable_curl() {
     fi
 
     if [[ "$response_code" != 200 ]]; then
-        [[ "$CURL_RAW_STATUS_CODE" == "true" ]] && printf '%s\n' "$raw_status_code" || printf '%s\n' "$response_code"
+        [[ "$CURL_USE_RAW_STATUS_CODE" == "true" ]] && printf '%s\n' "$raw_status_code" || printf '%s\n' "$response_code"
         return 1
     fi
 
-    [[ "$CURL_RAW_STATUS_CODE" == "true" ]] && printf '%s\n' "$raw_status_code" || printf '%s\n' "$response_code"
+    [[ "$CURL_USE_RAW_STATUS_CODE" == "true" ]] && printf '%s\n' "$raw_status_code" || printf '%s\n' "$response_code"
     return 0
 }
 
@@ -5743,12 +5748,11 @@ import_script() {
     if ! is_file "$script"; then
         error_exit "Failed to import script: $script"
     fi
-    source "$script" &>/dev/null || { error_exit "Failed to import script: $script"; }
+    source "$script" 2>/dev/null || { error_exit "Failed to import script: $script"; }
 }
 
 # Automatically import required scripts
 load_required_scripts() {
-    array_unique "BISU_REQUIRED_SCRIPTS"
     if ! is_array "BISU_REQUIRED_SCRIPTS"; then
         error_exit "Invalid BISU_REQUIRED_SCRIPTS array."
     fi
@@ -5799,6 +5803,25 @@ separate_command() {
 
     echo "(${rs[*]})"
     return 0
+}
+
+# verify utility's sig
+verify_sig() {
+    normalize_bool "VERIFY_BISU_SIG"
+    [[ "$VERIFY_BISU_SIG" == "true" ]] && {
+        local sig_status=$(verify_sig_file "$(bisu_file_path).asc" "$(bisu_file_path)")
+        string_starts_with "$sig_status" "ERR_" && {
+            error_exit "Invalid bisu signature, signature specific error: ${sig_status}"
+        }
+    }
+
+    normalize_bool "VERIFY_UTILITY_SIG"
+    [[ "$VERIFY_UTILITY_SIG" == "true" ]] && {
+        local sig_status=$(verify_sig_file "$(current_file_path).asc" "$(current_file_path)")
+        string_starts_with "$sig_status" "ERR_" && {
+            error_exit "Invalid utility signature, signature specific error: ${sig_status}"
+        }
+    }
 }
 
 # Register the current command
@@ -5857,22 +5880,6 @@ register_current_command() {
     }
     [ -n "$TARGET_DIR" ] && is_dir "$TARGET_DIR" || {
         TARGET_DIR=$(target_dir)
-    }
-
-    normalize_bool "VERIFY_BISU_SIG"
-    [[ "$VERIFY_BISU_SIG" == "true" ]] && {
-        local sig_status=$(verify_sig_file "$(bisu_file).asc" "$(bisu_file)")
-        string_starts_with "$sig_status" "ERR_" && {
-            error_exit "Invalid bisu signature, signature specific error: ${sig_status}"
-        }
-    }
-
-    normalize_bool "VERIFY_UTILITY_SIG"
-    [[ "$VERIFY_UTILITY_SIG" == "true" ]] && {
-        local sig_status=$(verify_sig_file "$(current_file).asc" "$(current_file)")
-        string_starts_with "$sig_status" "ERR_" && {
-            error_exit "Invalid utility signature, signature specific error: ${sig_status}"
-        }
     }
 }
 
@@ -5987,8 +5994,7 @@ safe_fork() {
     normalize_array "phrase"
     local cmd=$(array_get "phrase" 0)
     array_splice "phrase" 0 1
-    local args=""
-    args=$(trim "$(printf '%s ' "${phrase[@]}")")
+    local args=$(trim "$(printf '%s ' "${phrase[@]}")")
     phrase="$(printf '%s ' "${cmd} ${args}")"
 
     is_executable "$cmd" || {
@@ -5996,8 +6002,11 @@ safe_fork() {
         return 1
     }
 
-    local logging=$(trim "$2")
-    in_array "${logging}" "true" "false" || logging="true"
+    local async=$(trim "$2")
+    in_array "$async" "true" "false" || async="true"
+
+    local logging=$(trim "$3")
+    in_array "$logging" "true" "false" || logging="true"
 
     local max_forks="$SAFE_FORK_LIMIT"
     is_posi_int "$max_forks" || max_forks=16
@@ -6017,9 +6026,15 @@ safe_fork() {
             fi
 
             if [[ "$logging" == "true" ]]; then
-                eval "$(printf '%s' "$phrase")" | tee -a -- "$(current_log_file)"
+                eval "$(printf '%s' "$phrase")" | tee -a -- "$(current_log_file)" || {
+                    printf ''
+                    return 1
+                }
             else
-                eval "$(printf '%s' "$phrase")"
+                eval "$(printf '%s' "$phrase")" || {
+                    printf ''
+                    return 1
+                }
             fi
         } &
     elif command_exists "$cmd"; then
@@ -6029,25 +6044,35 @@ safe_fork() {
             else
                 exec 0</dev/tty 1>/dev/tty 2>/dev/null
             fi
-
             if [[ "$logging" == "true" ]]; then
-                bash -c "$(printf '%s' "$phrase")" | tee -a -- "$(current_log_file)"
+                bash -c "$(printf '%s' "$phrase")" | tee -a -- "$(current_log_file)" || {
+                    printf ''
+                    return 1
+                }
             else
-                bash -c "$(printf '%s' "$phrase")"
+                bash -c "$(printf '%s' "$phrase")" || {
+                    printf ''
+                    return 1
+                }
             fi
         } &
     fi
-
     local pid=$!
-    disown %+ &>/dev/null
-
     is_posi_int "$pid" || {
         printf ''
         return 1
     }
+    disown "$pid"
 
-    in_array "$fifo_exists" "true" "false" || fifo_exists="false"
-    [[ "$fifo_exists" == "true" ]] && printf '\n' >&3
+    if [[ "$async" == "false" ]]; then
+        wait "$pid"
+        local status=$?
+        [ "$status" -eq 0 ] || {
+            printf ''
+            return 1
+        }
+    fi
+
     printf '%s' "$pid"
     return 0
 }
@@ -6271,6 +6296,7 @@ callfunc() {
 # get the current utility's name.
 current_utility_name() {
     local utility_name=$(trim "$UTILITY_NAME")
+    [ -n "$utility_name" ] || utility_name=$(current_filename)
     printf '%s' "$utility_name"
 }
 
@@ -6314,6 +6340,21 @@ last_release_date() {
     printf '%s' "$last_release_date"
 }
 
+# Function to check if BISU is installed
+is_installed() {
+    local target_path=$(target_path)
+    is_file "$target_path" || return 1
+    return 0
+}
+
+# Check if it's currently in the target dir
+in_target_dir() {
+    local current_file_path="$(current_file_path)"
+    local target_path="$(target_path)"
+    [[ "$current_file_path" == "$target_path" ]] || return 1
+    return 0
+}
+
 # Integrate operations
 integrate_ops() {
     local args=$(get_args)
@@ -6334,13 +6375,15 @@ integrate_ops() {
         [[ "$action" == "$EMPTY_EXPR" ]] && action=""
     fi
 
+    in_array "$action" "install" || verify_sig
+
     set_action "$action"
     autorun_start
 
     local option_force=$(array_get "args" "f" "force")
     local option_yes=$(array_get "args" "y" "yes")
     local option_version=$(array_get "args" "v" "version")
-    local current_file=$(current_file)
+    local current_file_path=$(current_file_path)
     local current_filename=$(current_filename)
     local target_path=$(target_path)
     local is_matched_action="true"
@@ -6349,7 +6392,6 @@ integrate_ops() {
     "v" | "version")
         local version current_utility_name last_release_date
         current_utility_name="$(current_utility_name)"
-        [ -n "$current_utility_name" ] || current_utility_name="$(current_filename)"
         version="; $current_utility_name v$(current_utility_version)"
         last_release_date="$(last_release_date)"
         [ -n "$last_release_date" ] && {
@@ -6372,7 +6414,7 @@ integrate_ops() {
         printf '%s\n' "true"
         ;;
     "install")
-        [[ "$current_file" != "$target_path" ]] || {
+        in_target_dir && {
             error_exit "Duplicated paths. Aborted."
         }
 
@@ -6416,13 +6458,6 @@ integrate_ops() {
     fi
 }
 
-# Function to check if BISU is installed
-is_installed() {
-    local target_path=$(target_path)
-    is_file "$target_path" || return 1
-    return 0
-}
-
 # Function: install_script
 install_script() {
     if is_installed; then
@@ -6430,7 +6465,7 @@ install_script() {
         local date_str=$(date +'%Y%m')
         local uuid=$(uuidv4)
         local target_path=$(target_path)
-        local current_file=$(current_file)
+        local current_file_path=$(current_file_path)
         local bisu_filename=$(bisu_filename)
         local current_filename=$(current_filename)
         local backup_dir="$(user_backup_dir)/$date_str"
@@ -6444,32 +6479,40 @@ install_script() {
         log_msg "Your previous installation has been backed up to: $backup_path"
     fi
 
-    log_msg "Moving $current_filename to path: $target_path"
-    local is_installing_bisu verify_sig sig_file sig_file_target_path
-    # Is installing BISU
-    if [[ "$current_filename" == "$bisu_filename" ]]; then
-        is_installing_bisu="true"
-    else
-        is_installing_bisu="false"
-    fi
-
-    if [[ "$is_installing_bisu" == "true" ]]; then
+    local verify_sig sig_file sig_file_target_path
+    if is_bisu_file; then
         verify_sig="$VERIFY_BISU_SIG"
-        [[ "$verify_sig" == "true" ]] &&
-            command_exists "curl" && exec_command "curl -sL \"${BISU_ASC_FILE_URL}\" -o \"${current_file}.asc\"" 2>/dev/null
     else
         verify_sig="$VERIFY_UTILITY_SIG"
     fi
 
-    in_array "$verify_sig" "true" "false" || verify_sig="false"
+    normalize_bool "verify_sig" "false"
     if [[ "$verify_sig" == "true" ]]; then
-        sig_file="${current_file}.asc"
+        sig_file="${current_file_path}.asc"
         sig_file_target_path="${target_path}.asc"
-        is_file "$sig_file" && exec_command "mv \"$sig_file\" \"$sig_file_target_path\"" ||
-            error_exit "Failed to install $current_filename"
+        if ! is_file "$sig_file"; then
+            local sig_file_url
+            if is_bisu_file; then
+                sig_file_url=$(trim "$BISU_ASC_FILE_URL")
+            else
+                sig_file_url=$(trim "$UTILITY_ASC_FILE_URL")
+            fi
+
+            if is_valid_url "$sig_file_url"; then
+                CURL_RETRIES=5
+                CURL_RETRY_DELAY=3
+                local status_code=$(reliable_curl "$sig_file_url" "./${sig_file}")
+                [[ "$status_code" == "200" ]] || error_exit "Failed to install $current_filename"
+            fi
+        fi
     fi
 
-    exec_command "mv \"$current_file\" \"$target_path\"" "true" || error_exit "Failed to install $current_filename"
+    log_msg "Moving $current_filename to path: $target_path"
+    if [[ "$verify_sig" == "true" ]]; then
+        is_file "$sig_file" || error_exit "Failed to install $current_filename"
+        move_file "$sig_file" "$sig_file_target_path" || error_exit "Failed to install ${current_filename}, please check for permissions."
+    fi
+    move_file "$current_file_path" "$target_path" || error_exit "Failed to install ${current_filename}, please check for permissions."
     log_msg "Done."
 }
 
